import { env } from '@/env.mjs';

export const siteConfig = {
	title: 'Pemilyy - Your Digital Pet Clinic Companion',
	description:
		'Transitioning Your Pet Clinic into the Digital Age with Our Advanced Platform',
	keywords: () => [
		'pemilyy',
		'pemily',
		'pets',
		'cats',
		'dogs',
		'family',
		'familyy',
		'digital clinic',
		'pet clinic',
		'clinic',
		'pet health app',
		'animal hospital app',
		'pet medical records app',
		'software for veterinary clinics',
		'veterinary management system',
		'vet clinic software',
		'Veterinary Software',
		'Vet Clinic Software',
		'veterinary clinic app',
		'pet app for android',
		'Pet Health Record Keeper',
		'Veterinary Clinic App',
		'Online Vet Consultation',
		'pet clinic app',
		'veterinary appointment app',
		'Veterinary EMR Software',
		'Pet Health App',
		'Best Pet Care App',
		'Vet Appointment Booking',
		'Pet Medical Records App',
		'Pet Care Management',
		'Pet Clinic Management',
		'All-in-One Pet App',
		'Veterinary Appointment App',
		'Digital Vet Care',
		'Animal Hospital App',
		'Pet App for Android',
		'Mobile Pet Health Tracker',
		'Pet Vaccination Tracker',
		'Clinic Billing & Inventory',
		'Vet & Pet Parent Connect',
		'Pet Grooming & Health App',
		'Pet Pharmacy App',
		'Cloud-Based Vet App',
		'Pet Shop & Clinic App',
		'Pet Clinic Scheduling App',
		'Pet Health & Wellness App',
		'Digital Pet Care Platform',
		'Vet Hospital Management App',
		'Veterinary Business Software',
		'Smart Pet Care App',
		'Online Pet Clinic App',
		'Mobile Pet Healthcare',
		'Pet Treatment Tracker',
		'Pet Clinic POS System',
		'24/7 Pet Care App',
		'Veterinary Mobile Solutions',
		'Pet Diagnosis & Treatment App',
		'Online Vet Booking',
		'Vet Clinic Digital Transformation',
	],
	url: () => env.APP_URL,
	// googleSiteVerificationId: () => env.GOOGLE_SITE_VERIFICATION_ID || '',
};
